# This is a Redwing UI CICD workflow
name: F32INT - Redwing UI CICD

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contain jobs - <site>_preval,<site>_stage,<site>_preprb,<site>_<node>_contain,<site>_<node>_deploy,<site>_<node>_postval,<site>_<node>_rb,<site>_<node>_uncontain,<site>_log,<site>_notify
  f32int_preval:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Checks-out another repository
      - name: Check out Scripts repo
        uses: actions/checkout@master
        with:
          repository: cliew5/testtest
          token: ${{ secrets.token }}

      # Run pre-validate
      - name: Run pre-validate
        run: |
          echo "Begin pre-validate"

  f32int_stage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: f32int_preval
    environment:
      name: manual_approve
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: List files
        run: |
          echo $GITHUB_ENV

      # Run pre-validate
      - name: Run stage-file
        run: |
          echo "Begin stage-file"

  f32int_preprb:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: f32int_stage
    environment:
      name: manual_approve
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check out Scripts repo
        uses: actions/checkout@master
        with:
          repository: cliew5/testtest
          token: ${{ secrets.token }}

      - name: List file
        run: |
          ls
          ls -lrt

      - name: Create artifact file
        run: |
          echo $GITHUB_ENV
          echo $GITHUB_ENV
          mkdir Scripts
          touch Scripts/backupDirName.txt

      # Run backup
      - name: Run backup
        run: |
          echo "Begin backup"

      # Upload artifacts
      - name: Upload artifacts result
        uses: actions/upload-artifact@v3
        with:
          name: Scripts_backupDirName.txt
          path: Scripts/backupDirName.txt

  f32int_n1_contain:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: f32int_preprb
    environment:
      name: manual_approve
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: Scripts_backupDirName.txt
          path: Scripts/backupDirName.txt

      - name: List files
        run: |
          ls
          ls -lrt
          ls Scripts

      # Run contain
      -name: Run contain
       run: |
         echo "Begin contain"

      # Upload artifacts
      - name: Upload artifacts result
        uses: actions/upload-artifact@v3
        with:
          name: Scripts_backupDirName.txt
          path: Scripts/backupDirName.txt

  f32int_n2_contain:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: f32int_preprb
    environment:
      name: manual_approve
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

      # Run contain
      -name: Run contain
       run: |
         echo "Begin contain"

      # Upload artifacts
      - name: Upload artifacts result
        uses: actions/upload-artifact@v3
        with:
          name: Scripts_backupDirName.txt
          path: Scripts/backupDirName.txt

  f32int_n1_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: f32int_n1_contain
    environment:
      name: manual_approve
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

      # Run deploy
      -name: Run deploy
       run: |
         echo "Begin deploy"

      # Upload artifacts
      - name: Upload artifacts result
        uses: actions/upload-artifact@v3
        with:
          name: Scripts_backupDirName.txt
          path: Scripts/backupDirName.txt

  f32int_n2_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: f32int_n2_contain
    environment:
      name: manual_approve
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

      # Run deploy
      -name: Run deploy
       run: |
         echo "Begin deploy"

      # Upload artifacts
      - name: Upload artifacts result
        uses: actions/upload-artifact@v3
        with:
          name: Scripts_backupDirName.txt
          path: Scripts/backupDirName.txt

  f32int_n1_postval:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: f32int_n1_deploy
    environment:
      name: manual_approve
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

      # Run post-validate - health-check
      -name: Run post-validate - health-check
       run: |
         echo "Begin post-validate - health-check"

      # Upload artifacts
      - name: Upload artifacts result
        uses: actions/upload-artifact@v3
        with:
          name: Scripts_backupDirName.txt
          path: Scripts/backupDirName.txt

  f32int_n2_postval:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: f32int_n2_deploy
    environment:
      name: manual_approve
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

      # Run post-validate - health-check
      -name: Run post-validate - health-check
       run: |
         echo "Begin post-validate - health-check"

      # Upload artifacts
      - name: Upload artifacts result
        uses: actions/upload-artifact@v3
        with:
          name: Scripts_backupDirName.txt
          path: Scripts/backupDirName.txt

  f32int_n1_rb:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: f32int_n1_deploy
    environment:
      name: manual_approve
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

      # Run rollback
      -name: Run rollback
       run: |
         echo "Begin rollback"

  f32int_n2_rb:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: f32int_n2_deploy
    environment:
      name: manual_approve
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

      # Run rollback
      -name: Run rollback
       run: |
         echo "Begin rollback"

  f32int_n1_uncontain:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: f32int_n1_contain
    environment:
      name: manual_approve
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

      # Run uncontain
      -name: Run uncontain
       run: |
         echo "Begin uncontain"

  f32int_n2_uncontain:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: f32int_n2_contain
    environment:
      name: manual_approve
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

      # Run uncontain
      -name: Run uncontain
       run: |
         echo "Begin uncontain"

  f32int_log:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: f32int_preval
    environment:
      name: manual_approve
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

      # Run log-result
      -name: Run log-result
       run: |
         echo "Begin log-result"

  f32int_notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: f32int_preval
    environment:
      name: manual_approve
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

      # Run notify
      -name: Run log-result
       run: |
         echo "Begin notify"
