# This is a basic workflow to help you get started with Actions
name: Redwing UI CICD

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  f32int_preval:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

  # This workflow contains a single job called "build"
  f32int_stage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

  # This workflow contains a single job called "build"
  f32int_preprb:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

  # This workflow contains a single job called "build"
  f32int_n1_contain:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

  # This workflow contains a single job called "build"
  f32int_n2_contain:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV
		  
  # This workflow contains a single job called "build"
  f32int_n1_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

  # This workflow contains a single job called "build"
  f32int_n2_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

  # This workflow contains a single job called "build"
  f32int_n1_postval:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

  # This workflow contains a single job called "build"
  f32int_n2_postval:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

  # This workflow contains a single job called "build"
  f32int_n1_rb:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

  # This workflow contains a single job called "build"
  f32int_n2_rb:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

  # This workflow contains a single job called "build"
  f32int_n1_uncontain:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV

  # This workflow contains a single job called "build"
  f32int_n2_uncontain:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV
		  
  # This workflow contains a single job called "build"
  f32int_log:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV
		  
  # This workflow contains a single job called "build"
  f32int_notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Inject Version Details to the Application
        run: |
          echo $GITHUB_ENV